### ISSUE TITLE
Echec d'ajout de plusieurs bridges 

### ISSUE THREAD

**Issue by Sda79** [Manu-31/yane#2]
**Pour obtenir ce bug :** 
[yane.yml.zip](https://github.com/Manu-31/yane/files/1686076/yane.yml.zip)

Quand j'ajoute un deuxième bridge à mon réseau, les interfaces qui devraient être relié au 2e bridge n'ont pas été ajouté.

Après relecture du code j'ai repéré cette ligne :
https://github.com/Manu-31/yane/blob/1708d7a306400d7ee805d95f0801292d195ca957/yane_module_yaml#L102
Je pense qu'il faut la corriger par `for idx in ${!network_bridges__name[@]}`

Par contre une fois corrigée j'obtiens l'erreur yane suivante : `Destination device 'br1' can not accept interface 'br1i0'`
Après analyse je pense que le problème vient de cette fonction :
https://github.com/Manu-31/yane/blob/1708d7a306400d7ee805d95f0801292d195ca957/yane#L149-L168
J'ai pas encore trouvé de solution...

**Comment by Sda79** [comment]
Update
---------

J'ai réussi a fix le bug avec ces changements : 

- Fichier : `yane_module_bridge` ligne 29 : 
`intList=${bridgeInterfaces[$idx]}`
et ligne 46 : 
`if [ "${bridgeName["$1"]}" == "$1" ] ; then
    return 0
 fi`
- Fichier : `yane_module_yaml` ligne 102 : 
`for idx in ${!network_bridges__name[@]}`

**Comment by Sda79** [comment]
Ma solution semble régler le problème mais ca ne respecte plus le fait que
>\# bridgeName            array (name indexed) of BridgeName
>\# bridgeInterfaces      array (name indexed) of BridgeInterface

du coup je pense pas que ce soit une bonne solution parce que ca doit apporter d'autres bug...

**Comment by Sda79** [comment]
J'ai compris ! 
Il manque : `declare -A bridgeInterfaces` au fichier `yane`
Parce que on fait ici des dicos d'ailleurs @Manu-31 tu l'avais fait pour les autres variables initialisées par le module yaml. Sans doute un oubli. 
https://stackoverflow.com/questions/1494178/how-to-define-hash-tables-in-bash
Je vais commit le fix a toi de me dire ce que tu en penses.

**Comment by Manu-31** [comment]
Je ne comprenrs pas ta dernière remarque. A priori pas de soucis avec des modifications, ...
